---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - apt-get remove --purge zsh

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - sudo ansible-playbook -i ./tests/inventory ./tests/test_install.yml --syntax-check
  - sudo ansible-playbook -i ./tests/inventory ./tests/test_zshrc.yml --connection=local
  - sudo ansible-playbook -i ./tests/inventory ./tests/test_prompt.yml --connection=local
